# Generated by Django 2.2.16 on 2020-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20201125_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '6.1 TEXTO CONTACTO',
            },
        ),
    ]
