# Generated by Django 2.2.16 on 2020-11-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_introcontacto_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introcontacto',
            old_name='title',
            new_name='titulo',
        ),
    ]
