# Generated by Django 2.2.16 on 2020-11-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_auto_20201126_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='introcontacto',
            name='text_bold',
            field=models.TextField(blank=True, null=True),
        ),
    ]
