# Generated by Django 3.1.2 on 2020-11-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='actividades.tipoactividad'),
        ),
    ]
