# Generated by Django 2.2.16 on 2020-11-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20201120_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': '3.1 ACTIVIDADES'},
        ),
        migrations.AlterModelOptions(
            name='tipoactividad',
            options={'verbose_name_plural': '3. TIPO DE ACTIVIDAD'},
        ),
    ]
