# Generated by Django 2.2.16 on 2020-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_auto_20201125_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='icono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='titulo4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
