# Generated by Django 3.1.2 on 2020-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='frase',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='imagen_inicio',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
