# Generated by Django 3.1.2 on 2020-11-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20201112_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueHacemos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueQueremos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('text_boton', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name_plural': 'imagen+frase'},
        ),
    ]
