# Generated by Django 3.1.2 on 2020-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20201112_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quehacemos',
            options={'verbose_name_plural': 'que_hacemos'},
        ),
        migrations.AlterModelOptions(
            name='quequeremos',
            options={'verbose_name_plural': 'que_queremos'},
        ),
        migrations.RemoveField(
            model_name='quehacemos',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quequeremos',
            name='text_boton',
        ),
        migrations.AddField(
            model_name='quehacemos',
            name='text_boton',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quequeremos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
