# Generated by Django 3.1.2 on 2020-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20201112_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='title2',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
