# Generated by Django 3.1.2 on 2020-11-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_inicio_title2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name_plural': 'Inicio-info'},
        ),
    ]
