# Generated by Django 2.2.16 on 2020-11-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colabora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colabora',
            options={'verbose_name_plural': '5. COLABORA'},
        ),
    ]
