# Generated by Django 2.2.16 on 2020-11-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colabora', '0002_auto_20201125_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='colabora',
            name='link_payment',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
