# Generated by Django 3.1.2 on 2020-11-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20201120_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='lugar',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
