# Generated by Django 3.1.2 on 2020-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=400)),
                ('imagen_inicio', models.ImageField(upload_to='images')),
            ],
        ),
    ]
