# Generated by Django 2.2.16 on 2020-11-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_auto_20201120_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name_plural': '1 - INICIO'},
        ),
        migrations.AlterModelOptions(
            name='quehacemos',
            options={'verbose_name_plural': '1.3 - QUE HACEMOS'},
        ),
        migrations.AlterModelOptions(
            name='quequeremos',
            options={'verbose_name_plural': '1.2 - QUE QUEREMOS'},
        ),
    ]
