# Generated by Django 3.1.2 on 2020-11-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='icono4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
