# Generated by Django 3.1.2 on 2020-11-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_auto_20201114_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
