# Generated by Django 3.1.2 on 2020-11-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('text_boton', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('logo_name', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo2', models.CharField(blank=True, max_length=100, null=True)),
                ('destinatarios', models.TextField(blank=True, null=True)),
                ('titulo3', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tipoactividad')),
            ],
            options={
                'verbose_name_plural': 'actividades',
            },
        ),
    ]
