# Generated by Django 3.1.2 on 2020-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20201113_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='orden_en_pagina',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
