# Generated by Django 3.1.2 on 2020-11-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividad_orden_en_pagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='orden_en_pagina',
        ),
    ]
