# Generated by Django 3.1.2 on 2020-11-20 19:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_remove_actividad_orden_en_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
    ]
