# Generated by Django 3.1.2 on 2020-11-20 19:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_mi', '0003_auto_20201120_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='imagen_disco',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_disco'),
        ),
    ]
