# Generated by Django 3.1.2 on 2020-11-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_mi', '0004_auto_20201120_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
