# Generated by Django 2.2.16 on 2020-11-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_mi', '0005_auto_20201120_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disco',
            options={'verbose_name_plural': '2.1 DISCOS'},
        ),
        migrations.AlterModelOptions(
            name='sobremi',
            options={'verbose_name_plural': '2. SOBRE MUSICA LATTE'},
        ),
        migrations.AddField(
            model_name='sobremi',
            name='titulo0',
            field=models.TextField(blank=True, null=True),
        ),
    ]
