# Generated by Django 2.2.16 on 2020-11-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_mi', '0006_auto_20201125_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremi',
            name='descripcion0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sobremi',
            name='titulo0',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
