# Generated by Django 2.2.16 on 2020-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_mi', '0007_auto_20201125_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='colaborationes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disco',
            name='titulo1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
