# Generated by Django 2.2.16 on 2020-11-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_mi', '0008_auto_20201126_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco',
            old_name='colaborationes',
            new_name='colaboraciones',
        ),
    ]
