# Generated by Django 3.1.2 on 2020-11-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_disco', models.ImageField(blank=True, null=True, upload_to='images')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SobreMi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo2', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_marta', models.ImageField(blank=True, null=True, upload_to='images')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('titulo3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'sobre_mi',
            },
        ),
    ]
