# Generated by Django 3.1.2 on 2020-11-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre_mi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
