# Generated by Django 3.1.2 on 2020-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('icono1', models.CharField(blank=True, max_length=20, null=True)),
                ('link1', models.URLField(blank=True, null=True)),
                ('icono2', models.CharField(blank=True, max_length=20, null=True)),
                ('link2', models.URLField(blank=True, null=True)),
                ('icono3', models.CharField(blank=True, max_length=20, null=True)),
                ('link3', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'footer',
            },
        ),
    ]
