# Generated by Django 2.2.16 on 2020-11-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_auto_20201114_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': '7. PIE DE PAGINA'},
        ),
    ]
