# Generated by Django 2.2.16 on 2020-11-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0005_auto_20201125_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='link1',
        ),
    ]
