# Generated by Django 3.1.2 on 2020-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20201120_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='titulo',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
