# Generated by Django 3.1.2 on 2020-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_auto_20201121_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
