# Generated by Django 2.2.16 on 2020-11-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_auto_20201122_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name_plural': '4. FOTOS'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': '4.1 VIDEOS'},
        ),
    ]
